# ==============================================================================
# Generate code lists for ethnicity
# Author: SM Wu
# Date Created: 2025/08/01
# Date Updated: 2025/08/01
# The code list is generated by searching the dictionary terms and selected
# medcodes using grepl/!grepl rules. `code_type` is either "Ethnicity" or "Language".
# `ethnic_group` is deliberately non-missing; uncertain/general language or
# interpreter terms are assigned "unknown".
# 
# Details:
# 1) Set up and load data
# 2) Search for new relevant med codes
# 3) Create updated code lists
#
# Inputs:
# 1) Code_Lists/MASTER_Lists/CPRD_Aurum_Medical_10Feb2025.txt: Aurum medical master code list
# 2) Code_Lists/MASTER_Lists/CPRD_GOLD_Medical_23Feb2025.txt: GOLD medical master code list
# 3) Code_Lists/Ethnicity/Old/Aurum_Ethnicity_codelist_20230724_Alvin.txt: Old Aurum Ethnicity code list
# 4) Code_Lists/Ethnicity/Old/Gold_Ethnicity_codelist_20230724_Alvin.txt: Old GOLD Ethnicity code list
# 
# Intermediate outputs:
# 1) 
# 
# Final Outputs:
# 1) Code_Lists/Ethnicity/Aurum_Ethnicity_codelist_20250725.txt: Updated Aurum Ethnicity code list
# 2) Code_Lists/Ethnicity/Gold_Ethnicity_codelist_20250725.txt: Updated GOLD Ethnicity code list
# 3) Code_Lists/Ethnicity/Aurum_Gold_Ethnicity_new_codes_20250725.txt: Newly added Ethnicity codes for Aurum and GOLD

# ==============================================================================


# ================= 1) Set up and load data ====================================

# Clear memory
rm(list = ls())

# Packages
library(readr)
library(dplyr)
library(stringr)
library(tidyr)
library(readxl)


### For running in Data Safe Haven
# Set working directory
wd <- "S:/CDSTP_CPRD_25_005368/"
setwd(wd)

# Set input and output paths
path_input <- "SMI_GLP/Code_Lists/"
path_output <- "SMI_GLP/Code_Lists/Ethnicity/"

## Load data

# Read in Aurum medical dictionary
cprd_aurum_medical_raw <- 
  read_delim(
    paste0(wd, path_input, "MASTER_Lists/CPRD_Aurum_Medical_14Oct2025.txt"), 
    delim = "\t", escape_double = FALSE, 
    col_types = cols(MedCodeId = col_character(), 
                     OriginalReadCode = col_character(), 
                     CleansedReadCode = col_character(), 
                     SnomedCTConceptId = col_character(), 
                     SnomedCTDescriptionId = col_character()), 
    trim_ws = TRUE)
cprd_aurum_medical <- cprd_aurum_medical_raw %>%
  select(-Release) %>%
  rename(term = Term, medcodeid = MedCodeId) %>%
  mutate(term = str_to_lower(term))

# Read in Gold medical dictionary
cprd_gold_medical_raw <- 
  read_delim(
    paste0(wd, path_input, "MASTER_Lists/CPRD_GOLD_Medical_14Oct2025.txt"), 
    delim = "\t", escape_double = FALSE, 
    col_types = cols(medcode = col_character(), 
                     readcode = col_character()), 
    trim_ws = TRUE) 
cprd_gold_medical <- cprd_gold_medical_raw %>%
  rename(term = readterm) %>%
  mutate(term = str_to_lower(term))


# Read in old Ethnicity code list from 2024/03/21, setting all col types to character
# Aurum
ethn_codelist_aurum_old <- read_delim(
  paste0(wd, path_input, "Ethnicity/Old/Aurum_Ethnicity_codelist_20230724_Alvin.txt"),
  delim = "\t", escape_double = FALSE, 
  col_types = cols(medcodeid = col_character()),
  trim_ws = TRUE)
ethn_codelist_aurum_old_exeter <- read_delim(
  paste0(wd, path_input, "Ethnicity/Old/Aurum_Ethnicity_codelist_20260326_Exeter.txt"),
  delim = "\t", escape_double = FALSE, 
  col_types = cols(MedCodeId = col_character()),
  trim_ws = TRUE)

# Gold
ethn_codelist_gold_old <- read_delim(
  paste0(wd, path_input, "Ethnicity/Old/Gold_Ethnicity_codelist_20230724_Alvin.txt"),
  delim = "\t", escape_double = FALSE, 
  col_types = cols(medcode = col_character()),
  trim_ws = TRUE)



# ================= 2) Search for new relevant med codes =======================


### Aurum

aurum_ethn <- cprd_aurum_medical %>%
  filter(!is.na(term)) %>%
  # Inclusions: ethnicity-related terms by CleanedReadCode: 
  #   ^9T is ethnicity, ^9i is 2001 census ethnicity, ^9t is 2011 census ethnicity,  
  #   ^134 is origin and race
  filter(grepl(paste0("(?i)ethnic|\\bRace\\b|\\(NMO\\)|",
                      # broad racial/ethnic descriptors
                      "^white$|\\bblack\\b|^mixed$|\\basian\\b|",
                      "caucasoid|europeanoid|mongoloid|negroid|australoid|",
                      # White british
                      "^british$|^english$|^welsh$|^scottish$|^irish$|^ulster$|^cornish|",
                      "^white british$|^white scottish$|",
                      # White irish
                      "^irish$|irish traveller|white irish|",
                      # Other white
                      "^caucasian$|^european$|^polish$|^romanian$|^bulgarian$|^czech$|^slovak|",
                      "^slovenian$|^albanian$|^bosnian$|^croatian$|^serbian$|^kosovan$|^greek|",
                      "^cypriot$|^italian$|^portuguese$|^jewish$|^israeli$|\\bisraelite\\b|",
                      "^gypsy$|^romany|\\bRoma\\b|^australian$|^new zealand$|^pakeha$|",
                      "^baltic$|^estonian$|^latvian$|^lithuanian|^russian$|^ukrainian$|^turkish$",
                      # South asian
                      "\\bindian\\b|\\bIndian\\b|^pakistani$|^bangladeshi$|^bengali$|",
                      "^sylheti$|^sri lankan$|^punjabi$|^kashmiri$|^nepali$|^sinhalese$|",
                      # Other asian
                      "^chinese$|^japanese$|\\bkorean\\b|^filipino$|^malaysian$|^thai$|^vietnamese$|^burmese$|^myanmar$|",
                      "indonesian$|^malaysian$|",
                      # Caribbean
                      "\\bcaribbean\\b|\\bguyana\\b|^barbadian$|^jamaican$|^saint lucian$|",
                      # African
                      "african$|^nigerian$|^somali$|^ethiopian$|^eritrean$|^angolan$|^kenyan$|",
                      "^senegalese$|central african republic|",
                      # Middle eastern/north african
                      "arab$|^afghan$|^iraqi$|^iranian$|^moroccan$|^yemeni$|^north african$|^middle eastern$|^kurdish$|",
                      # Other
                      "latin american$|^south american$|^samoan$|^maori$|^fijian$|^tongan$|^tokelauan$|",
                      "niuean$|^cook island$|^new zealand$|^pakeha|^other ethnic"),
               trimws(term)) | 
           grepl("^9T|^9i|^9t|^134", CleansedReadCode, ignore.case=FALSE)) %>%
  
  # Exclusions: assessments, disorders, negations, generic
  
  filter(!grepl(
    paste0("(?i)", # case-insensitive
           # assessment and disorders
           "difficulty|clinic|disorder|sign|therapist|therapy|informed consent|",
           "does not|service|problems|ability|able to|cognitive|impairment|advice|",
           "score|exam|inventory|screening|braille|scale|assessment|development|",
           "body language|speech|measure|delay|analysis|care activity|barrier|",
           "programme|test|repetitious|compression|ostomy|adverse|blood|",
           "piedra|tongue|faeces|magic|carer|adenoma|heel|eye|poison|exposure|",
           "toe|benign|dermatose|stool|ringworm|head|snake|vomit|thinking|hair|",
           "colour|thigh|identification|tick|desert|tarry|ringworm|stools|cattle|",
           "ovalocytosis|tuberculosis|data|cirrhosis|sick cell|",
           # negations
           "declined|refusal|refuse|not required|not recorded|unknown|race not stated|",
           "ethnic category not state|",
           # language/birthplace/religion
           "born|birth|country of origin nos|language|interpreter|read|church|catholic|orthodox|",
           # unrelated
           "parent|bushman|inappropriate|telephone|foul|pastie|father|religion|mother|",
           "diet|coffee|rubber|food|",
           # generic entries
           "^race$|^ethnicity$|^country of origin$|^born in - country$|^o/e - ethnic group$|",
           "^ethnic category|^ethnic group|",
           "language nos$|^translator/interpreter$|^second language|^world language|",
           "interpreter present|interpreter$|interpreter not|^interpreter needed$|",
           "^interpreter$|booked|additional|comprehend|automatic language|",
           "further interpreter needed|general|interlingua|indicator|^language$|",
           "finding|approach|commonly spoken|preference|regime|latin$|latin interpreter|",
           "latin language|other interpreter|other main spoken language|",
           "^preferred spoken language$|^preferred written lanugage$|romance language|",
           "use of language$|first language not english|english not main spoken"), 
    term, perl = TRUE))
  
  # # Inclusions: language, interpreter, country of birth
  # 
  # # Also include ethnicity-related terms by CleanedReadCode: 
  # #   ^9T is ethnicity, ^9i is 2001 census ethnicity, ^9t is 2011 census ethnicity,  
  # #   ^134 is origin and race
  # filter(grepl("(?i)language|interpreter|^country of birth|^born in|^reads", term) | 
  #          grepl("^9T|^9i|^9t|^134", CleansedReadCode, ignore.case=FALSE)) %>%
  # 
  # # Exclusions: assessments, disorders, negations, generic
  # 
  # filter(!grepl(
  #   paste0("(?i)", # case-insensitive
  #          # assessment and disorders
  #          "difficulty|clinic|disorder|sign|therapist|therapy|informed consent|",
  #          "does not|service|problems|ability|able to|cognitive|impairment|advice|",
  #          "score|exam|inventory|screening|braille|scale|assessment|development|",
  #          "body language|speech|measure|delay|analysis|care activity|barrier|",
  #          "programme|test|repetitious|",
  #          # negations
  #          "declined|refusal|not required|not recorded|unknown|race not stated|",
  #          "ethnic category not state|",
  #          # unrelated
  #          "parent|bushman|inappropriate|telephone|foul|",
  #          # generic entries
  #          "^race$|^ethnicity$|^country of origin$|^born in - country$|",
  #          "language nos$|^translator/interpreter$|^second language|^world language|",
  #          "interpreter present|interpreter$|interpreter not|^interpreter needed$|",
  #          "^interpreter$|booked|additional|comprehend|automatic language|",
  #          "further interpreter needed|general|interlingua|indicator|^language$|",
  #          "finding|approach|commonly spoken|preference|regime|latin$|latin interpreter|",
  #          "latin language|other interpreter|other main spoken language|",
  #          "^preferred spoken language$|^preferred written lanugage$|romance language|",
  #          "use of language$|first language not english|english not main spoken"), 
  #   term, perl = TRUE))
  
  # filter(!grepl(
  #   paste0("(?i)child|parental|clinic|second|inappropriate|foul|body|further|",
  #          # assessment and disorders
  #          "test|difficulty|disorders?|delay|scale|speech|assistant|score|",
  #          "alphabet|therapy|sign|impairment|nos|referral|therapist|telephone|",
  #          "measure|verbal language|development|inventory|scheme|remediation|",
  #          "assess|use language|comprehend|use of language|ability|finding|",
  #          "provision|barrier|advice|braille|request|analysis|schizophrenic|",
  #          "exercises|approach|regimes|stimulation|element|program|observation|",
  #          # negations
  #          "refus|not needed|not recorded|not present|not available|",
  #          "declined|",
  #          # generic language entries
  #          "read$|spoken$|spoken - finding|preferred spoken language|^language$|",
  #          "language commonly spoken in europe|world languages|written language$|",
  #          "^interpreter$|first language|language finding|interpreter booked|",
  #          "indo-european|afro-asiatic|translator/interpreter|presence|",
  #          "^interpreter needed$|^interpreter present$|^language interpreter$|",
  #          "^need for interpreter$|^main spoken language$|additional|",
  #          "^uses language$|other interpreter"), 
  #   term, perl = TRUE))

# Subset to terms not already included in old Ethnicity code list
aurum_new_ethn <- aurum_ethn %>%
  filter(!(medcodeid %in% ethn_codelist_aurum_old$medcodeid))

# Which terms were in the old list but are not included in the new list,
# filtering to those terms in the code dictionary
aurum_ethn_miss_from_new <- ethn_codelist_aurum_old %>%
  filter(!(medcodeid %in% aurum_ethn$medcodeid)) %>% 
  filter(medcodeid %in% cprd_aurum_medical$medcodeid)

aurum_ethn_miss_from_new_exeter <- ethn_codelist_aurum_old_exeter %>%
  filter(!(MedCodeId %in% aurum_ethn$medcodeid)) %>% 
  filter(MedCodeId %in% cprd_aurum_medical$medcodeid)


# Gold

gold_ethn <- cprd_gold_medical %>%
  filter(!is.na(term)) %>%
  # Inclusions: ethnicity-related terms by CleanedReadCode: 
  #   ^9T is ethnicity, ^9i is 2001 census ethnicity, ^9t is 2011 census ethnicity,  
  #   ^134 is origin and race
  filter(grepl(paste0("(?i)ethnic|\\bRace\\b|\\(NMO\\)|",
                      # broad racial/ethnic descriptors
                      "^white$|\\bblack\\b|^mixed$|\\basian\\b|",
                      "caucasoid|europeanoid|mongoloid|negroid|australoid|",
                      # White british
                      "^british$|^english$|^welsh$|^scottish$|^irish$|^ulster$|^cornish|",
                      "^white british$|^white scottish$|",
                      # White irish
                      "^irish$|irish traveller|white irish|",
                      # Other white
                      "^caucasian$|^european$|^polish$|^romanian$|^bulgarian$|^czech$|^slovak|",
                      "^slovenian$|^albanian$|^bosnian$|^croatian$|^serbian$|^kosovan$|^greek|",
                      "^cypriot$|^italian$|^portuguese$|^jewish$|^israeli$|\\bisraelite\\b|",
                      "^gypsy$|^romany|\\bRoma\\b|^australian$|^new zealand$|^pakeha$|",
                      "^baltic$|^estonian$|^latvian$|^lithuanian|^russian$|^ukrainian$|^turkish$",
                      # South asian
                      "\\bindian\\b|\\bIndian\\b|^pakistani$|^bangladeshi$|^bengali$|",
                      "^sylheti$|^sri lankan$|^punjabi$|^kashmiri$|^nepali$|^sinhalese$|",
                      # Other asian
                      "^chinese$|^japanese$|\\bkorean\\b|^filipino$|^malaysian$|^thai$|^vietnamese$|^burmese$|^myanmar$|",
                      "indonesian$|^malaysian$|",
                      # Caribbean
                      "\\bcaribbean\\b|\\bguyana\\b|^barbadian$|^jamaican$|^saint lucian$|",
                      # African
                      "african$|^nigerian$|^somali$|^ethiopian$|^eritrean$|^angolan$|^kenyan$|",
                      "^senegalese$|central african republic|",
                      # Middle eastern/north african
                      "arab$|^afghan$|^iraqi$|^iranian$|^moroccan$|^yemeni$|^north african$|^middle eastern$|^kurdish$|",
                      # Other
                      "latin american$|^south american$|^samoan$|^maori$|^fijian$|^tongan$|^tokelauan$|",
                      "niuean$|^cook island$|^new zealand$|^pakeha"),
               trimws(term)) | 
           grepl("^9T|^9i|^9t|^134", readcode, ignore.case=FALSE)) %>%
  
  # Exclusions: assessments, disorders, negations, generic
  
  filter(!grepl(
    paste0("(?i)", # case-insensitive
           # assessment and disorders
           "difficulty|clinic|disorder|sign|therapist|therapy|informed consent|",
           "does not|service|problems|ability|able to|cognitive|impairment|advice|",
           "score|exam|inventory|screening|braille|scale|assessment|development|",
           "body language|speech|measure|delay|analysis|care activity|barrier|",
           "programme|test|repetitious|compression|ostomy|adverse|blood|",
           "piedra|tongue|faeces|magic|carer|adenoma|heel|eye|poison|exposure|",
           "toe|benign|dermatose|stool|ringworm|head|snake|vomit|thinking|hair|",
           "colour|thigh|identification|tick|desert|tarry|ringworm|stools|cattle|",
           "ovalocytosis|tuberculosis|data|cirrhosis|sick cell|",
           # negations
           "declined|refusal|refuse|not required|not recorded|unknown|race not stated|",
           "ethnic category not state|",
           # language/birthplace/religion
           "born|birth|country of origin nos|language|interpreter|read|church|catholic|orthodox|",
           # unrelated
           "parent|bushman|inappropriate|telephone|foul|pastie|father|religion|mother|",
           "diet|coffee|rubber|food|",
           # generic entries
           "^race$|^ethnicity$|^country of origin$|^born in - country$|^o/e - ethnic group$|",
           "^ethnic category|^ethnic group|",
           "language nos$|^translator/interpreter$|^second language|^world language|",
           "interpreter present|interpreter$|interpreter not|^interpreter needed$|",
           "^interpreter$|booked|additional|comprehend|automatic language|",
           "further interpreter needed|general|interlingua|indicator|^language$|",
           "finding|approach|commonly spoken|preference|regime|latin$|latin interpreter|",
           "latin language|other interpreter|other main spoken language|",
           "^preferred spoken language$|^preferred written lanugage$|romance language|",
           "use of language$|first language not english|english not main spoken"), 
    term, perl = TRUE))

# Subset to terms not already included in old Ethnicity code list
gold_new_ethn <- gold_ethn %>%
  filter(!(medcode %in% ethn_codelist_gold_old$medcode))

# Which terms were in the old list but are not included in the new list,
# filtering to those terms in the code dictionary
gold_ethn_miss_from_new <- ethn_codelist_gold_old %>%
  filter(!(medcode %in% gold_ethn$medcode)) %>% 
  filter(medcode %in% cprd_gold_medical$medcode)


# # Combine Aurum and GOLD new Ethnicity codes
# aurum_gold_SMI_new_codes <- list(
#   Aurum = aurum_new_ethn,
#   Gold = gold_new_ethn)
# # Save lists of newly added codes into one .xlsx file on separate tabs
# write.xlsx(aurum_gold_SMI_new_codes,
#            file = paste0(wd, path_output, "Aurum_Gold_SMI_new_codes_25Jul2025.xlsx"),
#            overwrite = TRUE)

# ================= 3) Add in ethnicity categorizations ===============================


# 17-category labels and search criteria
ethnic_group_lookup <- data.frame(
  ethnic_group = 1:17,
  ethnic_group_name = c(
    "1=White British",
    "2=White Irish",
    "3=Other White",
    "4=White and Black Caribbean",
    "5=White and Black African",
    "6=White and Asian",
    "7=Other Mixed",
    "8=Indian",
    "9=Pakistani",
    "10=Bangladeshi",
    "11=Other Asian",
    "12=Caribbean",
    "13=African",
    "14=Other Black",
    "15=Chinese",
    "16=Other",
    "17=Unknown"
  )
)

rx <- function(x) paste0("(", paste(x, collapse = "|"), ")")
has <- function(x, pattern) grepl(pattern, x, ignore.case = TRUE, perl = TRUE)
not_has <- function(x, pattern) !has(x, pattern)

assign_ethnic_group <- function(term) {
  t <- trimws(tolower(term))
  
  case_when(
    # 17 Unknown / not stated / refused / not recorded. Put first so these do
    # not get pulled into an ethnicity category simply because they contain the
    # word "ethnic".
    has(t, rx(c("unknown", "not recorded", "not given", "not stated", "refused", 
              "declined", "ethnic group nos", "ethnic groups \\(census\\) nos", 
              "patient ethnicity unknown"))) ~ "17=Unknown",
    
    # Mixed groups before single-group categories.
    has(t, rx(c("white.*black caribbean", "black caribbean.*white", "black/white"))) ~ "4=White and Black Caribbean",
    has(t, rx(c("white.*black african", "black african.*white", "afro-caucasian"))) ~ "5=White and Black African",
    has(t, rx(c("white.*asian", "asian.*white", "chinese and white"))) ~ "6=White and Asian",
    has(t, rx(c("mixed", "multiple", "black and asian", "black and chinese", "black and white",
              "afro-caucasian", "other ethnic.*mixed", "black.*asian", 
              "asian.*carib", "other ethnic.*black/white", "other ethnic.*asian/white"))) & 
      not_has(t, paste0("black - other|non-mixed|mixed black|mixed asian|other mixed white|",
                        "mixed european|mixed irish and other white|british or mixed british")) ~ "7=Other Mixed",
    
    # Asian subcategories before broader Asian.
    has(t, rx(c("\\bindian\\b", "british indian", "indian sub-continent", "punjabi", "kashmiri"))) &
      not_has(t, "west indian|indo-caribbean|black indian") ~ "8=Indian",
    has(t, rx(c("pakistani", "mirpuri"))) ~ "9=Pakistani",
    has(t, rx(c("bangladeshi", "bengali", "sylheti"))) ~ "10=Bangladeshi",
    has(t, rx(c("chinese", "cantonese", "mandarin"))) ~ "15=Chinese",
    
    # Black subcategories before broader Black.
    has(t, rx(c("african", "nigerian", "somali", "ethiopian", "eritrean", "amharic", 
                "tigrinya", "oromo", "swahili", "yoruba", "igbo", "lingala", "akan", "kenyan",
                "twi", "zulu", "shona", "ndebele", "brawa", "kongo", "hausa", "angolan",
                "fulah", "kanuri", "bambara", "ewe", "herero", "kuanyama", "luba-katanga",
                "chewa", "nyanja", "chichewa", "southern sotho", "senegalese"))) &
      not_has(t, paste0("white.*black african|black african.*white|east african asian|",
                        "north african|n african|arab")) ~ "13=African",
    has(t, rx(c("caribbean", "west indian", "guyana", "indo-caribbean", "barbadian", 
                "jamaican", "saint lucian", "afro-caribbean"))) &
      not_has(t, "white.*black caribbean|black caribbean.*white|asian") ~ "12=Caribbean",
    has(t, rx(c("other black", "black", "negroid", "black british", "black arab",
              "black iranian", "black north african", "black indian sub-continent",
              "black east african asian", "black e afric asian"))) ~ "14=Other Black",
    
    # White subcategories before other white.
    has(t, rx(c("white british", "british", "mixed british", "eng/?welsh/?scot", "english",
              "welsh", "scottish", "northern irish", "ulster scots", "cornish", "northern ireland"))) & 
      not_has(t, "asian|arab|african|ethnic minority") ~ "1=White British",
    has(t, rx(c("white irish", "\\birish\\b"))) &
      not_has(t, "mixed irish|gypsy|traveller.*gypsy|traveller") ~ "2=White Irish",
    has(t, rx(c("other white", "white:", "white -", "white", "white ethnic", "white background",
              "caucasian", "caucasoid", "european", "europeanoid", "polish",
              "romanian", "bulgarian", "czech", "slovak", "sloven", "albanian", "yugoslavia",
              "bosnian", "croatian", "serbian", "kosovan", "greek", "cypriot",
              "italian", "portuguese", "jewish", "israeli", "gypsy", "romany", "gypsies",
              "roma", "traveller", "australian", "new zealand european", "pakeha",
              "north american", "baltic", "estonian", "latvian", "lithuanian",
              "russian", "ukrainian", "commonwealth \\(russian\\) indep states"))) &
      not_has(t, "mid east") ~ "3=Other White",
    
    # Remaining Asian and Other groups.
    has(t, rx(c("other asian", "asian", "japanese", "korean", "filipino", "malaysian",
              "sri lankan", "tamil", "sinhalese", "nepali", "thai", "vietnamese",
              "burmese", "myanmar", "indonesian", "javanese", "sundanese", "malay",
              "tagalog", "pashto", "pushto", "urdu", "guj[ae]rati", "hindi", "asian/indo-carib (nmo)",
              "marathi", "konkani", "telugu", "malayalam", "uighur", "tibetan",
              "far eastern", "mongoloid", "oriental", "sikh", "hindu", "buddhist"))) ~ "11=Other Asian",
    has(t, rx(c("other ethnic", "other", "other group", "arab", "arabic", "iranian", "farsi",
              "persian", "dari", "kurdish", "turkish", "azerbaijani", "turkmen", "afghan", "iraqi",
              "tajik", "tatar", "kazakh", "kirghiz", "middle eastern", "north african", "n african",
              "moroccan", "yemeni", "latin american", "south american", "central american", 
              "australoid", "fijian", "samoan", "tongan", "tokelauan", "niuean", "cook island",
              "maori", "new zealand", "pacific", "nauru", "tahitian", "marshallese", "hiri motu",
              "chamorro", "bislama", "inuktitut", "inupiaq", "greenlandic", "kalaallisut",
              "quechua", "guarani", "aymara", "navajo", "cree", "ojibwa", "ojibwe",
              "divehi", "dhivehi", "malagasy", "tetum", "haitian", "creole", "british ethnic minority",
              "mauritian", "seychellois", "maldivian", "st helena", "armenian", "muslim"))) ~ "16=Other",
    
    # Less-specific demographic labels.
    has(t, "non-white|brit\\. ethnic minor") ~ "16=Other",
    
    TRUE ~ "17=Unknown"
  )
}

aurum_ethn_groups <- aurum_ethn %>%
  mutate(
    ethnic_group = assign_ethnic_group(term),
    # fix a few assignments
    ethnic_group = case_when(
      term %in% c("cypriot (part not stated) - ethnic category 2001 census") ~ "3=Other White",
      term == "new zealand ethnic group nos" ~ "16=Other",
      TRUE ~ ethnic_group),
    ethnic_group = factor(ethnic_group, levels = ethnic_group_lookup$ethnic_group_name),
    ethnic_group_num = factor(ethnic_group, levels = ethnic_group_lookup$ethnic_group_name,
                              labels = ethnic_group_lookup$ethnic_group),
  )

gold_ethn_groups <- gold_ethn %>%
  mutate(
    ethnic_group = assign_ethnic_group(term),
    # fix a few assignments
    ethnic_group = case_when(
      term %in% c("cypriot (part not stated) - ethnic category 2001 census") ~ "3=Other White",
      term == "new zealand ethnic group nos" ~ "16=Other",
      TRUE ~ ethnic_group),
    ethnic_group = factor(ethnic_group, levels = ethnic_group_lookup$ethnic_group_name),
    ethnic_group_num = factor(ethnic_group, levels = ethnic_group_lookup$ethnic_group_name,
                              labels = ethnic_group_lookup$ethnic_group),
  )

# Check categorizations
temp <- aurum_ethn_groups %>%
  left_join(ethn_codelist_aurum_old_exeter, by = join_by(medcodeid == MedCodeId))
temp2 <- temp %>% filter(ethnic_group_num != eth16)


# ================= 4) Save updated code lists ===============================


# Create updated code lists

# Aurum
ethn_codelist_aurum_new <- aurum_ethn_groups

# Gold
ethn_codelist_gold_new <- gold_ethn_groups


# Save updated code lists
write.table(ethn_codelist_aurum_new,
            file = paste0(wd, path_output, "Aurum_Ethnicity_codelist_20260601.txt"),
            sep = "\t", row.names = FALSE)

write.table(ethn_codelist_gold_new,
            file = paste0(wd, path_output, "Gold_Ethnicity_codelist_20260601.txt"),
            sep = "\t", row.names = FALSE)



